baseURL = "https://casahugo.github.io/blog/"
languageCode = "fr-fr"
title = "Hugo Casabella"
theme = "resume-hugo"
publishDir = "docs"

[params]
    firstName = "Hugo"
    lastName = "Casabella"
    address = "Lyon, France"
    contactNote = "Lead web developer" #used in QR code only
    profileImage = "img/me.jpeg"
    email = "hugo.casabella@gmail.com"
    description = "Autodidacte et passionné par le web depuis bientôt 10ans, j'aime développer, partager et trouver des solutions."
    description2 = "Développeur expérimenté, mes différentes expériences m'ont permis d'encadrer et d'organiser des équipes afin de répondre à de nombreux challenges techniques."
    description3 = "Spécialisé en PHP j'aime aussi travailler en Javascript ou en GO et utiliser des technos comme RabbitMQ, Docker ou Serverless."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = false
    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/hugo-casabella-15b01a163/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/casahugo"

#[params.google.analytics]
#    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]